-- -- 1. Dodajemy tymczasową kolumnę z prawidłowym typem
-- ALTER TABLE sales_data_sample ADD (temp_date DATE);
--
-- -- 2. Konwertujemy tekst na datę (Oracle sam to przeliczy)
-- UPDATE sales_data_sample
-- SET temp_date = TO_DATE(ORDERDATE, 'MM/DD/YYYY HH24:MI');
--
-- -- 3. Porządki: usuwamy tekstową, zmieniamy nazwę nowej
-- ALTER TABLE sales_data_sample DROP COLUMN ORDERDATE;
-- ALTER TABLE sales_data_sample RENAME COLUMN temp_date TO ORDERDATE;


-- Zadanie 2
-- Znormalizuj tabelę TEMP tworząc tabele, które będą przechowywać dane reprezentujące odpowiednie obiekty lub
-- zdarzenia (np. zamówienie, produkt, klient, etc.). Każda kolumna z tabeli źródłowej powinna znaleźć się w jednej z
-- docelowych tabel. Zanim stworzysz schemat sprawdź jakie zależności opisują dane w poszczególnych kolumnach tabeli
-- TEMP (czyli np. czy dane zamówienie dotyczy więcej niż jednego produktu, czy dany produkt należy tylko do jednej
-- kategorii produktu, etc.). Utworzone tabele powinny posiadać klucze główne nieinteligentne inne niż identyfikatory w
-- tabeli TEMP. Pamiętaj o utworzeniu odpowiednich więzów integralności.

drop table zs1_customers;
create table zs1_customers(
    id_customer number generated by default as identity primary key,
    customername varchar2(100) not null,
    phone varchar2(25),
    addressline1 varchar2(100),
    addressline2 varchar2(100),
    city varchar2(50),
    state varchar2(50),
    postalcode varchar2(20),
    country varchar2(50),
    territory varchar2(20),
    contactlastname varchar2(50),
    contactfirstname varchar2(50)
);

drop table zs1_products;
create table zs1_products(
    id_product number(8) primary key, -- tu mamy trigger do tego
    productcode varchar2(20) unique not null,
    productline varchar2(50),
    msrp number(8, 2)
);

drop table zs1_orders;
create table zs1_orders(
    id_order number generated by default as identity primary key,
    ordernumber number(10) unique not null,
    orderdate date,
    status varchar2(20),
    qtr_id number(1),
    month_id number(2),
    year_id number(4),
    id_customer number(8) not null,

    foreign key (id_customer) references zs1_customers(id_customer)
);

drop table zs1_order_details;
create table zs1_order_details(
    id_order_detail number generated by default as identity primary key,
    id_order number(8) not null,
    id_product number(8) not null,
    quantityordered number(4),
    priceeach number(10, 2),
    orderlinenumber number(3),
    sales number(10, 2),
    dealsize varchar2(10),

    foreign key (id_order) references zs1_orders(id_order),
    foreign key (id_product) references zs1_products(id_product)
);

-- Zadanie 2
-- Żeby pokazać, że umiemy :D
drop sequence seq_prod;
create sequence seq_prod;

drop trigger t_set_id_products;
create or replace trigger t_set_id_products
    before insert on zs1_products for each row
    begin
        :new.id_product:=seq_prod.nextval;
    end;

-- Zadanie 4
-- Napisz pakiet, który będzie się składał z następujących podprogramów:
-- (a) procedury (lub procedur), która z tabeli TEMP przepisze odpowiednio dane do tabel utworzonych w Zadaniu 2.
-- Uwaga: Jeśli wielokrotnie wywołujemy procedurę(-y) z pakietu, tabele z Zadania 2 powinny zawierać odpowiednio
-- jedną miejscowość o podanej nazwie, jednego klienta o podanej nazwie, jedno zamówienie o określonym numerze, czy
-- też jeden produkt o podanym kodzie, etc. Ładując dane do odpowiednich tabel wykorzystaj również przetwarzanie
-- masowe (np. przy ładowaniu danych do jednej z tabel).
-- (b) dwóch dowolnych funkcji, które powinny być zaimplementowane w oparciu o tabele utworzone w Zadaniu 2.
-- Funkcje nie powinny odwoływać się do danych z tabeli TEMP.

create or replace package pack_zs1 as

end pack_zs1;

declare
    cursor c1 is
        select CUSTOMERNAME,
               PHONE,
               ADDRESSLINE1,
               ADDRESSLINE2,
               CITY,
               STATE,
               POSTALCODE,
               COUNTRY,
               TERRITORY,
               CONTACTLASTNAME,
               CONTACTFIRSTNAME
        from TEMP;

        type NameSet is table of c1%rowtype;
        customers NameSet;
    begin
    select CUSTOMERNAME,
               PHONE,
               ADDRESSLINE1,
               ADDRESSLINE2,
               CITY,
               STATE,
               POSTALCODE,
               COUNTRY,
               TERRITORY,
               CONTACTLASTNAME,
               CONTACTFIRSTNAME
    from TEMP
    where 
end;


