drop table ZS2_CUSTOMER;
create table ZS2_CUSTOMER(
    ID_CUSTOMER number generated by default as identity primary key,
    customername varchar2(100),
    phone varchar2(25)
);

drop table ZS2_LOCATION;
create table ZS2_LOCATION(
    id_location number generated by default as identity primary key,
    city varchar2(50),
    state varchar2(50),
    territory varchar2(20),
    country varchar2(50)
);

drop table zs2_time;
create table zs2_time(
    id_time number generated by default as identity primary key,
    "DATE" date,
    day_of_week number(1),
    is_weekend number(1),
    day_name varchar2(25),
    month_name varchar2(25),
    month_num number(2),
    qtr_num number(1),
    year number(4)
);

drop table zs2_product;
create table zs2_product(
    id_product number generated by default as identity primary key,
    productcode varchar2(20),
    productline varchar2(50),
    msrp number(8,2)
);

drop table zs2_sales;
create table zs2_sales(
    id_sales number generated by default as identity primary key,
    id_time not null,
    id_product not null,
    id_customer not null,
    id_location not null,
    quantityordered number(4),
    priceeach number(10,2),
    sales number(10,2),

    foreign key (id_time) references zs2_time(id_time),
    foreign key (id_product) references ZS2_PRODUCT(id_product),
    foreign key (id_customer) references ZS2_CUSTOMER(id_customer),
    foreign key (id_location) references ZS2_LOCATION(id_location)
);

truncate table ZS2_PRODUCT;
insert into zs2_product (
    id_product,
    productcode,
    productline,
    msrp
)
select
    id_product,
    productcode,
    productline,
    msrp
from zs1_products;

insert into zs2_customer (
    id_customer,
    customername,
    phone
)
select
    id_customer,
    customername,
    phone
from zs1_customers;

truncate table zs2_location;

insert into zs2_location (
    city,
    state,
    territory,
    country
)
select
    city,
    state,
    max(territory),
    country
from zs1_customers
group by
    city,
    state,
    country;

create or replace function zs2_is_weekend(f_date in date
) return number is
    f_day varchar2(10);
begin
    f_day := to_char(f_date, 'dy', 'nls_date_language=english');

    if f_day in ('sat', 'sun') then
        return 1;
    else
        return 0;
    end if;
end;

truncate table zs2_time;
insert into zs2_time (
    "DATE",
    day_of_week,
    is_weekend,
    day_name,
    month_name,
    month_num,
    qtr_num,
    year
)
select distinct
    orderdate,
    to_char(orderdate, 'd'),
    zs2_is_weekend(ORDERDATE),
    to_char(orderdate, 'day'),
    to_char(orderdate, 'month'),
    to_char(orderdate, 'mm'),
    to_char(orderdate, 'q'),
    to_char(orderdate, 'yyyy')
from zs1_orders;

truncate table zs2_sales;
insert into zs2_sales (
    id_time,
    id_product,
    id_customer,
    id_location,
    quantityordered,
    priceeach,
    sales
)
select
    t.id_time,
    od.id_product,
    o.id_customer,
    l.id_location,
    od.quantityordered,
    od.priceeach,
    od.sales
from zs1_order_details od
         join zs1_orders o on od.id_order = o.id_order
         join zs1_customers c on o.id_customer = c.id_customer
         join zs2_time t on o.orderdate = t."DATE"
         join zs2_location l on (
    c.city = l.city and
    nvl(c.state, 'n/a') = nvl(l.state, 'n/a') and
    c.country = l.country
);

commit;

select count(*) from ZS2_PRODUCT;
select count(*) from ZS2_LOCATION;
select count(*) from ZS2_CUSTOMER;
select count(*) from ZS2_SALES;
select count(*) from ZS2_TIME;